---
#- name: Generate inventory
#  hosts: localhost
#  roles:
#    - tripleo_inventory

- name: Install LogTool
  hosts: undercloud
  gather_facts: no
  vars:
    logtool_action: '{{ install.logtool }}'
    logtool_dir: '/home/stack/LogTool/Plugin_for_Infrared/'

  tasks:

  - name: Create LogTool Start Script (logtool.sh)
    template:
      src: logtool.sh.j2
      dest: /home/stack/logtool.sh
      group: stack
      mode: 0744

  - name: Execute LogTool Start Script
    command: /home/stack/logtool.sh
    #register: logtool

#  - name: P/F - If Report file exists (F), print its content
#    shell: ls /home/stack/LogTool/Plugin_for_Infrared/LogTool_Report.log
#    register: report_file_exists
#    command: cat /home/stack/LogTool/Plugin_for_Infrared/LogTool_Report.log
#    when : report_file_exists == 0



  - name: Check for Report File existence
    stat:
     path: /home/stack/LogTool/Plugin_for_Infrared/LogTool_Report.log
    register: report_log_stat

  - debug:
      var: report_log_stat

  - name:
    block:
      - name: Read content of Report File
        shell: cat /home/stack/LogTool/Plugin_for_Infrared/LogTool_Report.log
        register: report_log_content

      - name: Print content of Report File
        debug:
          var: report_log_content
    when: report_log_stat.stat.exists



#  - name: Check LogTool result files for Overcloud logs
#    shell: grep "Total Number of Errors/Warnings is:" *.log
#    args:
#      chdir: "{{ overcloud_result_dir }}"
#    register: log_output
#
#
#  - name: Check LogTool result files for Undercloud logs
#    shell: grep "Total Number of Errors/Warnings is:" *.log
#    args:
#      chdir: "{{ undercloud_result_dir }}"
#    register: log_output
#
#
#
#  - name: Print errors
#    debug:
#      var: log_output

