---
#- name: Generate inventory
#  hosts: localhost
#  roles:
#    - tripleo_inventory

- name: Install LogTool
  hosts: undercloud
  gather_facts: no
  vars:
    logtool_action: '{{ install.logtool }}'
    overcloud_result_dir: '/home/stack/LogTool/Plugin_for_Infrared/Overcloud_ERROR_Log_Tool_Results'
    undercloud_result_dir: '/home/stack/LogTool/Plugin_for_Infrared/Overcloud_ERROR_Log_Tool_Results'

  tasks:

  - name: Create LogTool Start Script (logtool.sh)
    template:
      src: logtool.sh.j2
      dest: /home/stack/logtool.sh
      group: stack
      mode: 0744


  - name: Execute LogTool Start Script
    command: /home/stack/logtool.sh
    #register: logtool

  - name: Check LogTool result files for Overcloud logs
    shell: grep "Total Number of Errors/Warnings is:" *.log
    args:
      chdir: "{{ overcloud_result_dir }}"
    register: log_output


  - name: Check LogTool result files for Undercloud logs
    shell: grep "Total Number of Errors/Warnings is:" *.log
    args:
      chdir: "{{ undercloud_result_dir }}"
    register: log_output



  - name: Print errors
    debug:
      var: log_output

